In [1]:
# Dependencies
import pandas as pd
import glob

In [2]:
# Merging csv files (without repeating header)
citibike_files = glob.glob("*.csv") 
df = pd.concat((pd.read_csv(f, header = 0) for f in citibike_files))
df

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0.0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,1.0,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,2.0,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,3.0,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,4.0,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36916,NaN,2828,2020-06-30 23:53:19.7380,2020-07-01 00:40:28.5760,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,18351,Customer,1969,0
36917,NaN,2729,2020-06-30 23:54:44.0100,2020-07-01 00:40:13.6470,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,44401,Customer,1969,0
36918,NaN,2788,2020-06-30 23:54:52.1920,2020-07-01 00:41:20.6500,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42334,Customer,1969,0
36919,NaN,2702,2020-06-30 23:56:14.6650,2020-07-01 00:41:16.7820,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42463,Customer,1969,0
36920,NaN,2649,2020-06-30 23:57:46.1490,2020-07-01 00:41:55.5060,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42468,Customer,1998,2

In [3]:
# Export file as a CSV
df.to_csv("2020-citibike-tripdata_JantoJun.csv")